services:
  nest:
    container_name: links-back
    build:
      context: .
      dockerfile: ./deploy/dockerfile
    ports:
      - '${LINKS_PORT}:${LINKS_PORT}'
    networks:
      - postgres-network
    environment:
      DATABASE_URL: ${DATABASE_URL}

networks:
  postgres-network:
    external: true
