services:
  db:
    image: docker.io/postgres:17-alpine
    container_name: links-db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - links-network

  links-back:
    container_name: links-back
    build:
      context: .
      dockerfile: ./deploy/dockerfile
    ports:
      - '${LINKS_PORT}:${LINKS_PORT}'
    depends_on:
      - db
    networks:
      - links-network
    environment:
      DATABASE_URL: ${DATABASE_URL}

volumes:
  postgres_data:
    driver: local

networks:
  links-network:
    driver: bridge
